apiVersion: v1
kind: Service
metadata:
  name: jenkins-poc
  labels:
    app: jenkins-poc
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: worker
    port: 50000
    targetPort: 50000
    protocol: TCP
  selector:
    app: jenkins-poc