apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-poc
  labels:
    app: jenkins-poc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins-poc
    spec:
      securityContext:
        fsGroup: 757
      containers:
      - name: jenkins-poc
        image: ibmicpcoc/jenkins-icp:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        ports:
        - containerPort: 8080
        - containerPort: 50000
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkinspvc
