apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
    selector:
      matchLabels:
        app: {{ template "fullname" . }}
    replicas: {{ .Values.replicaCount }}
    template:
      metadata:
        labels:
          app: {{ template "fullname" . }}
      spec:
        containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.Version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: 9080
