apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-sumapp-service"
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: NodePort
  ports:
    - targetPort: 9080
      port: 80
      protocol: TCP
      name: "http"
  selector:
    app: {{ template "fullname" . }}
