apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ template "name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: worker
    port: 50000
    targetPort: 50000
    protocol: TCP
  selector:
    app: {{ template "name" . }}
