## This metadata is used to augment the value.yaml to drive ICP UI for configuration of the Helm chart installation

image:
  pullPolicy:
    __metadata:
      name: "pullPolicy"
      label: "Docker image pull policy"
      description: "Always, Never, or IfNotPresent. Defaults to IfNotPresent"
      type: "string"
      immutable: "false"
      required: true
      options:
      - label: "IfNotPresent"
        value: "IfNotPresent"
      - label: "Always"
        value: "Always"
      - label: "Never"
        value: "Never"
