apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ template "name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  - name: ssh
    port: 22
    targetPort: 3022
    protocol: TCP
  selector:
    app: {{ template "name" . }}
