apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app:  {{ template "name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  - port: 22
    protocol: TCP
    name: ssh
  selector:
    app: {{ template "name" . }}
