apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ template "name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.http.port }}
    targetPort: {{ .Values.service.http.targetPort }}
    protocol: TCP
  - name: ssh
    port: {{ .Values.service.ssh.port }}
    targetPort: {{ .Values.service.ssh.targetPort }}
    protocol: TCP
  selector:
    app: {{ template "name" . }}
