# IBM Guestbook image version ibmcom/guestbook:v1

replicaCount: 2

guestbook:
  image: ibmicpcoc/guestbook:v2
  pullPolicy: Always
  service:
    type: NodePort

redis:
  image: ibmicpcoc/redis:5.0.4
  pullPolicy: Always

redisSlave:
  image: ibmicpcoc/redis-slave:5.0.4
  pullPolicy: Always


