apiVersion: v1
description: A simple Node.js application used to explore Kubernetes deployments.
name: kubetoy
version: 1.9.0
icon: https://ibm-icp-coc.github.io/charts/repo/stable/duck.png
keywords:
- toy
- amd64
- ppc64le
- s390x
- ICP
- kubernetes
- s3