## This metadata is used to augment the value.yaml to drive ICP UI for configuration of the Helm chart installation
arch:
  __metadata:
    label: "Architecture scheduling preferences"
  amd64:
    __metadata:
      name: "amd64"
      label: "AMD64 scheduling preference"
      description: "Architecture preference for target worker node."
      type: "string"
      immutable: false
      required: true
      options:
      - label: "0 - Do not use"
        value: 0
      - label: "1 - Least preferred"
        value: 1
      - label: "2 - No preference"
        value: 2
      - label: "3 - Most preferred"
        value: 3
 
  ppc64le:
    __metadata:
      name: "ppc64le"
      label: "PPC64LE scheduling preference"
      description: "Architecture preference for target worker node."
      type: "string"
      immutable: false
      required: true
      options:
      - label: "0 - Do not use"
        value: 0
      - label: "1 - Least preferred"
        value: 1
      - label: "2 - No preference"
        value: 2
      - label: "3 - Most preferred"
        value: 3
  
  s390x:
    __metadata:
      name: "s390x"
      label: "S390X scheduling preference"
      description: "Architecture preference for target worker node."
      type: "string"
      immutable: false
      required: true
      options:
      - label: "0 - Do not use"
        value: 0
      - label: "1 - Least preferred"
        value: 1
      - label: "2 - No preference"
        value: 2
      - label: "3 - Most preferred"
        value: 3 
cos:
  __metadata:
    label: "Use Cloud Object Storage (S3)"
    description: "Experiment with shared object (S3) storage."
  useCloudObjectStorage:
    __metadata:
      label: "Connect to S3 object storage"
      description: "Enables the cloud object storage page, which allows you to create, remove and view objects in S3 storage."
      type: "boolean"
      immutable: "false"
      required: true
  bucket:
    __metadata:
      label: "Bucket Name"
      description: "The name of an existing bucket in storage."
      type: "string"
      immutable: false
      required: false
  endpoint:
    __metadata:
      label: "Endpoint"
      description: "The endpoint URI to send requests to. The default endpoint is built from the configured region. The endpoint should be a string like 's3.us.cloud-object-storage.appdomain.cloud'."
      type: "string"
      immutable: false
      required: false
  accessKeyId:
    __metadata:
      label: "Access Key Id"
      description: "Your access key ID for AWS or Softlayer"
      type: "string"
      immutable: false
      required: false
  secretAccessKey:
    __metadata:
      label: "Secret Access Key"
      description: "Your secret access key ID for AWS or Softlayer"
      type: "string"
      immutable: false
      required: false
  
storage:
  __metadata:
    label: "Use Shared Storage"
  useSharedStorage:
    __metadata:
      name: "useSharedStorage"
      label: "Enable persistence for this deployment"
      description: "Enables persistence for this deployment. Defaults to false. A persistent volume is required if true."
      type: "boolean"
      immutable: "false"
      required: true
  useStorageClass:
    __metadata:
       name: "useStorageClass"
       label: "Use dynamic storage class for this persistent volume claim."
       description: "Enables the use of dynamically provisioned storage based on a storage class."
       type: "boolean"
       immutable: "false"
       required: true
  createPvc:
    __metadata:
      name: "createPvc"
      label: "Create a new PVC"
      description: "Will create a new PVC, requesting 1Gi of storage and the specified access mode.  If set to false then it will try to use an existing PVC."
      type: "boolean"
      immutable: "false"
      required: true
  accessMode:
     __metadata:
       name: "accessMode"
       label: "PVC access mode"
       description: "ReadWriteOnce, ReadOnlyMany, or ReadWriteMany."
       type: "string"
       immutable: false
       required: true
       options:
       - label: "ReadWriteOnce"
         value: "ReadWriteOnce"
       - label: "ReadOnlyMany"
         value: "ReadOnlyMany"
       - label: "ReadWriteMany"
         value: "ReadWriteMany"
image:
  pullPolicy:
    __metadata:
      name: "pullPolicy"
      label: "Docker image pull policy"
      description: "Always, Never, or IfNotPresent. Defaults to IfNotPresent"
      type: "string"
      immutable: "false"
      required: true
      options:
      - label: "IfNotPresent"
        value: "IfNotPresent"
      - label: "Always"
        value: "Always"
      - label: "Never"
        value: "Never"
