# Default values for kubetoy.
arch:
  amd64: 2
  ppc64le: 2
  s390x: 2
replicaCount: 3
image:
  repository: ibmicpcoc/kubetoy
  pullPolicy: IfNotPresent
storage:
  useSharedStorage: false
  createPvc: false
  useStorageClass: false
  storageClassName: "glusterfs"
  accessMode: "ReadWriteMany"
cos:
  useCloudObjectStorage: false
  bucket: ""
  endpoint: ""
  accessKeyId: ""
  secretAccessKey: ""