# Default values for kubetoy.
replicaCount: 3
image:
  repository: ibmicpcoc/kubetoy
  pullPolicy: IfNotPresent
service:
  name: kubetoy-service
  type: NodePort
storage:
  useSharedStorage: true
  createPvc: true
  pvc: kubetoy-pvc
  accessmode: ReadWriteMany
