## This metadata is used to augment the value.yaml to drive ICP UI for configuration of the Helm chart installation

storage:
  __metadata:
    label: "Storate"
  useSharedStorage:
   __metadata:
      name: "useSharedStorage"
      label: "Enable persistence for this deployment"
      description: "Enables persistence for this deployment. Defaults to false. A persistent volume is required if true."
      type: "boolean"
      immutable: "false"
      required: true
  createPvc:
   __metadata:
      name: "createPvc"
      label: "Create a new PVC"
      description: "Will create a new PVC, requesting 1Gi of storage and the specified access mode."
      type: "boolean"
      immutable: "false"
      required: true
