# Default values for kubetoy.
arch:
  amd64: 2
  ppc64le: 2
  s390x: 2
replicaCount: 3
image:
  repository: ibmicpcoc/kubetoy
  pullPolicy: IfNotPresent
service:
  name: kubetoy-service
  type: NodePort
storage:
  useSharedStorage: false
  createPvc: false
  pvc: kubetoy-pvc
  useStorageClass: false
  storageClassName: "glusterfs"
  accessMode: "ReadWriteMany"
