# Default values for kubetoy.
replicaCount: 3
image:
  repository: ibmicpcoc/kubetoy
  pullPolicy: IfNotPresent
service:
  name: kubetoy-service
  type: NodePort
storage:
  useSharedStorage: false
  createPvc: true
  pvc: kubetoy-pvc
  useStorageClass: false
  storageClassName: "standard"
  accessMode: "ReadWriteMany"
