qoddb:
  replicaCount: 1
  image:
    repository: ibmicpcoc/qod-db
    tag: 1.0.0
    pullPolicy: Always

qodapi:
  replicaCount: 1
  image:
    repository: ibmicpcoc/qod-api
    tag: 1.0.0
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 3000   

qodweb:
  replicaCount: 1
  image:
    repository: ibmicpcoc/qod-web
    tag: 1.0.0
    pullPolicy: Always
  service:
    type: NodePort
    port: 3001

