apiVersion: v1
appVersion: "1.0.0"
description: Quote of the Day application.  A three tiered web app that dishes up a new quote every day from a database of over 70k quotes from famous people.
name: qod
version: 1.0.0
icon: https://ibm-icp-coc.github.io/charts/repo/stable/quote.png
keywords:
- node.js
- web
- three tier
- mariadb
- quotes
