# Default values for qod.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

qoddb:
  replicaCount: 1
  image:
    repository: ibmicpcoc/qod-db
    tag: 1.0.0
    pullPolicy: IfNotPresent

qodapi:
  replicaCount: 1
  image:
    repository: ibmicpcoc/qod-api
    tag: 1.0.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3000   

qodweb:
  replicaCount: 1
  image:
    repository: ibmicpcoc/qod-web
    tag: 1.0.0
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 3001
