image:
  repository: ibmicpcoc/jenkins-icp
  tag: latest
  pullPolicy: IfNotPresent
serviceAccount: 
  useServiceAccount: false
  name: jenkins
service:
  name: jenkins-icp-svc
  type: NodePort
storage:
  createNewPvc: true
  pvc: jenkins-icp-pvc
  accessMode: ReadWriteOnce
  size: 5Gi