## This metadata is used to augment the value.yaml to drive ICP UI for configuration of the Helm chart installation

storage:
  __metadata:
    label: "Create new PVC"
  createNewPvc:
    __metadata:
      name: "createNewPvc"
      label: "Create a new PVC for this deployment."
      description: "If enabled a new PVC with the name specified will be created. Otherwise it will assume that one with teh given name is already created and will be used."
      type: "boolean"
      immutable: "false"
      required: true
serviceAccount:
  __metadata:
    label: "Service Account"
  createNewPvc:
    __metadata:
      name: "useServiceAccount"
      label: "Specify the service account name to use when not deployed to default namespace."
      description: "If you are deploying Jenkis to a namespace other than default, then you need to provide a service account."
      type: "boolean"
      immutable: "false"
      required: true
image:
  pullPolicy:
    __metadata:
      name: "pullPolicy"
      label: "Docker image pull policy"
      description: "Always, Never, or IfNotPresent. Defaults to IfNotPresent"
      type: "string"
      immutable: "false"
      required: true
      options:
      - label: "IfNotPresent"
        value: "IfNotPresent"
      - label: "Always"
        value: "Always"
      - label: "Never"
        value: "Never"