apiVersion: v1
kind: Service
metadata:
  name: {{ include "guestbook.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "guestbook.name" . }}
    helm.sh/chart: {{ include "guestbook.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.guestbook.service.type }}
  ports:
  - name: http-server
    port: 3000
    targetPort: http-server
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "guestbook.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
