{{- if .Values.redis.slaveEnabled -}}
apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    app: redis
    role: slave
spec:
  ports:
  - name: redis-server
    port: {{ .Values.redis.port }}
    targetPort: redis-server
    protocol: TCP
  selector:
    app: redis
    role: slave
{{- end }}
