apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
spec:
  ports:
  - name: redis-server
    port: {{ .Values.redis.port }}
    targetPort: redis-server
  selector:
    app: redis
    role: master
