apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: master
      version: master   # this is what kiali keys off of
  template:
    metadata:
      labels:
        app: redis
        role: master
        version: master
    spec:
      containers:
      - name: redis-master
        image: "{{ .Values.redis.image }}"
        imagePullPolicy: {{ .Values.redis.pullPolicy }}
        ports:
        - name: redis-server
          containerPort: 6379
