apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
spec:
  ports:
  - name: redis-server
    port: 6379
    targetPort: redis-server
    protocol: TCP
  selector:
    app: redis
    role: master
