replicaCount: 1
image:
  repository: ibmicpcoc/jenkins-icp
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: jenkins-icp-svc
  type: NodePort
storage:
  pvc: jenkins-icp-pvc
  accessMode: ReadWriteOnce
  size: 5Gi