---
kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-kubetoy-configmap-env"
data:
  ENV_TOY_CONFIGMAP: 'This is a configuration value.'
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-kubetoy-secret-env"
type: Opaque
data:
  ENV_TOY_SECRET: VGhpcyBpcyBhIHRlc3Q=
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-kubetoy-configmap-files"
data:
  config.json: '{ "default": "123" }'
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-kubetoy-secret-files"
type: Opaque
data:
  toy-secret.txt: U2hoLi4uIFRoaXMgaXMgYSBzZWNyZXQu
# {{ if .Values.cos.useCloudObjectStorage  }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-kubetoy-cos-configmap"
data:
  cos-credentials.json: '{ "bucket": "{{ .Values.cos.bucket }}", "endpoint": "{{ .Values.cos.endpoint }}", "accessKeyId": "{{ .Values.cos.accessKeyId }}", "secretAccessKey": "{{ .Values.cos.secretAccessKey }}" }'
# {{ end }}