---
kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-configmap-env"
data:
  ENV_TOY_CONFIGMAP: 'This is a configuration value.'
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret-env"
type: Opaque
data:
  ENV_TOY_SECRET: VGhpcyBpcyBhIHRlc3Q=
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-configmap-files"
data:
  config.json: '{ "default": "123" }'
  version.txt: 'v1.6.1'
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret-files"
type: Opaque
data:
  toy-secret.txt: U2hoLi4uIFRoaXMgaXMgYSBzZWNyZXQu
