apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-kubetoy-service"
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app: {{ template "fullname" . }}
