replicaCount: 1
image:
  repository: gogs/gogs
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: gog-icp-svc
  type: LoadBalancer
  http.port: 80
  http.targetPort: 3000
  ssh.port: 22
  ssh.targetPort: 22
storage:
  pvc: gog-icp-pvc
  accessMode: ReadWriteOnce
  size: 20Gi